######################################################################
# Automatically generated by qmake (1.06c) Sun Jan 2 17:59:20 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h maptable.h newdialog.h tile.h
SOURCES += crpgmapedit.cpp mainwindow.cpp maptable.cpp newdialog.cpp tile.cpp
